[tool.poetry]
name = "whatispyspark"
version = "0.1.0"
description = ""
authors = ["soungryoul-kim <soungryoul.kim>"]

[tool.poetry.dependencies]
python = "^3.8"
pyspark = {extras = ["pandas_on_spark", "sql"], version = "^3.3.0"}
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
